// Code generated by cobragen; DO NOT EDIT.

package list

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "apikey.list",
			Path:         []string{"apikey", "list"},
			Use:          "list",
			Short:        "List API keys",
			Aliases:      []string{"ls"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "DescribeAPIKeyListResponse",
				Description: "API key list response.",
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"apikey"}, Use: "apikey", Short: "Manage API keys", Long: "Manage API keys for AGR sandbox access.", Aliases: []string{"ak", "key"}},
		},
		API: apicli.APISpec{
			Action:       "DescribeAPIKeyList",
			RequestType:  "DescribeAPIKeyListRequest",
			ResponseType: "DescribeAPIKeyListResponse",
		},
		DisableRequestFlag: true,
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
