// Code generated by cobragen; DO NOT EDIT.

package get

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "pre-cache-image-task.get",
			Path:         []string{"pre-cache-image-task", "get"},
			Use:          "get <image-digest> --image <image> --image-registry-type <type>",
			Short:        "Describe an image pre-cache task",
			SupportsJSON: true,
			Args: []command.ArgSpec{
				{Name: "image-digest", Required: true, Description: "Image digest."},
			},
			Output: command.OutputSpec{
				DataType:    "DescribePreCacheImageTaskResponse",
				Description: "Image pre-cache task response.",
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"pre-cache-image-task"}, Use: "pre-cache-image-task", Short: "Manage image pre-cache tasks", Aliases: []string{"pre_cache_image_task"}},
		},
		API: apicli.APISpec{
			Action:       "DescribePreCacheImageTask",
			RequestType:  "DescribePreCacheImageTaskRequest",
			ResponseType: "DescribePreCacheImageTaskResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "Image",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "image", Flag: "image", Usage: "Image reference (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "ImageDigest",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "image-digest", Positional: true},
				},
			},
			{
				Name:     "ImageRegistryType",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "image-registry-type", Flag: "image-registry-type", Usage: "Image registry type: enterprise or personal (required)", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
