// Code generated by cobragen; DO NOT EDIT.

package update

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "tool.update",
			Path:         []string{"tool", "update"},
			Use:          "update <tool-id>",
			Short:        "Update a sandbox tool",
			SupportsJSON: true,
			Args: []command.ArgSpec{
				{Name: "tool-id", Required: true, Description: "Sandbox tool ID."},
			},
			Output: command.OutputSpec{
				DataType:    "UpdateSandboxToolResponse",
				Description: "Sandbox tool update response.",
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"tool"}, Use: "tool", Short: "Manage sandbox tools", Long: "Manage sandbox tools (templates). Tools define the type and capabilities of sandbox instances.", Aliases: []string{"t"}},
		},
		API: apicli.APISpec{
			Action:       "UpdateSandboxTool",
			RequestType:  "UpdateSandboxToolRequest",
			ResponseType: "UpdateSandboxToolResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "ToolId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "tool-id", Positional: true},
				},
			},
			{
				Name:   "Description",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "description", Flag: "description", Shorthand: "d", Usage: "Tool description", Type: command.FlagString},
				},
			},
			{
				Name:   "NetworkConfiguration",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "network-configuration", Flag: "network-configuration", Usage: "NetworkConfiguration as JSON object, @file, or - for stdin", Type: command.FlagString},
				},
			},
			{
				Name:   "Tags",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "tags", Flag: "tags", Usage: "Tags as JSON array, @file, or - for stdin", Type: command.FlagString},
				},
			},
			{
				Name:   "CustomConfiguration",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "custom-configuration", Flag: "custom-configuration", Usage: "CustomConfiguration JSON object, @file, or - for stdin", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
