// Code generated by cobragen; DO NOT EDIT.

package commands

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
	apicall "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/api/call"
	apikeycreate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/apikey/create"
	apikeydelete "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/apikey/delete"
	apikeylist "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/apikey/list"
	instancebrowservnc "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/browser/vnc"
	instancecoderun "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/code/run"
	instancecreate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/create"
	instancedebug "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/debug"
	instancedelete "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/delete"
	instanceexec "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/exec"
	instancefiledownload "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/file/download"
	instancefileupload "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/file/upload"
	instanceget "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/get"
	instancelist "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/list"
	instancelogin "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/login"
	instancemobileadb "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/mobile/adb"
	instancemobileconnect "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/mobile/connect"
	instancemobiledisconnect "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/mobile/disconnect"
	instancemobilelist "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/mobile/list"
	instancemobiletunnel "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/mobile/tunnel"
	instancepause "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/pause"
	instanceproxy "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/proxy"
	instanceresume "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/resume"
	instanceupdate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/instance/update"
	precacheimagetaskcreate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/precacheimagetask/create"
	precacheimagetaskget "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/precacheimagetask/get"
	toolcreate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/tool/create"
	tooldelete "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/tool/delete"
	toolget "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/tool/get"
	toollist "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/tool/list"
	toolupdate "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/tool/update"
)

func Registry() (*command.Registry, error) {
	registry := command.NewRegistry()
	for _, module := range []command.Module{
		apicall.Module(),
		apikeycreate.Module(),
		apikeydelete.Module(),
		apikeylist.Module(),
		instancebrowservnc.Module(),
		instancecoderun.Module(),
		instancecreate.Module(),
		instancedebug.Module(),
		instancedelete.Module(),
		instanceexec.Module(),
		instancefiledownload.Module(),
		instancefileupload.Module(),
		instanceget.Module(),
		instancelist.Module(),
		instancelogin.Module(),
		instancemobileadb.Module(),
		instancemobileconnect.Module(),
		instancemobiledisconnect.Module(),
		instancemobilelist.Module(),
		instancemobiletunnel.Module(),
		instancepause.Module(),
		instanceproxy.Module(),
		instanceresume.Module(),
		instanceupdate.Module(),
		precacheimagetaskcreate.Module(),
		precacheimagetaskget.Module(),
		toolcreate.Module(),
		tooldelete.Module(),
		toolget.Module(),
		toollist.Module(),
		toolupdate.Module(),
	} {
		if err := registry.Register(module); err != nil {
			return nil, err
		}
	}
	return registry, nil
}
