// Code generated by cobragen; DO NOT EDIT.

package create

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "apikey.create",
			Path:         []string{"apikey", "create"},
			Use:          "create",
			Short:        "Create a new API key",
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "CreateAPIKeyResponse",
				Description: "API key create response.",
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"apikey"}, Use: "apikey", Short: "Manage API keys", Long: "Manage API keys for AGR sandbox access.", Aliases: []string{"ak", "key"}},
		},
		API: apicli.APISpec{
			Action:       "CreateAPIKey",
			RequestType:  "CreateAPIKeyRequest",
			ResponseType: "CreateAPIKeyResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:   "Name",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "name", Flag: "name", Shorthand: "n", Usage: "Name for the API key (required)", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
