// Code generated by cobragen; DO NOT EDIT.

package list

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "instance.list",
			Path:         []string{"instance", "list"},
			Use:          "list",
			Short:        "List instances",
			Long:         "List sandbox instances with optional filters.",
			Examples:     []string{"agr instance list", "agr instance list --tool-id sdt-xxxx", "agr instance list --filters '[{\"Name\":\"Status\",\"Values\":[\"RUNNING\"]}]'", "agr instance list --offset 0 --limit 50"},
			Aliases:      []string{"ls"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "DescribeSandboxInstanceListResponse",
				Description: "Instance list response.",
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"instance"}, Use: "instance", Short: "Manage sandbox instances", Long: "Manage sandbox instances and related data-plane workflows.", Aliases: []string{"i"}},
		},
		API: apicli.APISpec{
			Action:       "DescribeSandboxInstanceList",
			RequestType:  "DescribeSandboxInstanceListRequest",
			ResponseType: "DescribeSandboxInstanceListResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:   "InstanceIds",
				Parser: "common.default_string_array",
				Inputs: []apicli.InputSpec{
					{Name: "instance-ids", Flag: "instance-ids", Usage: "Filter by instance IDs", Format: "--instance-ids <id1> --instance-ids <id2>", Examples: []string{"agr instance list --instance-ids ins-xxxx", "agr instance list --instance-ids ins-xxxx --instance-ids ins-yyyy"}, Type: command.FlagStringArray},
				},
			},
			{
				Name:   "ToolId",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "tool-id", Flag: "tool-id", Usage: "Filter by tool ID", Type: command.FlagString},
				},
			},
			{
				Name:   "Offset",
				Parser: "common.default_int",
				Inputs: []apicli.InputSpec{
					{Name: "offset", Flag: "offset", Usage: "Pagination offset", Type: command.FlagInt},
				},
			},
			{
				Name:   "Limit",
				Parser: "common.default_int",
				Inputs: []apicli.InputSpec{
					{Name: "limit", Flag: "limit", Usage: "Pagination limit (max 100)", Type: command.FlagInt},
				},
			},
			{
				Name:   "Filters",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "filters", Flag: "filters", Usage: "Additional filters as JSON array, @file, or - for stdin", Format: "[{\"Name\":\"<field>\",\"Values\":[\"<value1>\",\"<value2>\"]}]", Examples: []string{"agr instance list --filters '[{\"Name\":\"Status\",\"Values\":[\"RUNNING\"]}]'", "agr instance list --filters '[{\"Name\":\"Status\",\"Values\":[\"RUNNING\",\"STARTING\"]}]'", "agr instance list --filters '[{\"Name\":\"Status\",\"Values\":[\"RUNNING\"]},{\"Name\":\"ToolName\",\"Values\":[\"my-tool\"]}]'"}, Values: []string{"Status: STARTING, RUNNING, STOPPING, STOPPED, STOP_FAILED, FAILED", "ToolName: tool name used to create the instance", "ToolId: tool ID"}, Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
