// Code generated by cobragen; DO NOT EDIT.

package list

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "tool.list",
			Path:         []string{"tool", "list"},
			Use:          "list",
			Short:        "List available tools",
			Aliases:      []string{"ls"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "DescribeSandboxToolListResponse",
				Description: "Sandbox tool list response.",
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"tool"}, Use: "tool", Short: "Manage sandbox tools", Long: "Manage sandbox tools (templates). Tools define the type and capabilities of sandbox instances.", Aliases: []string{"t"}},
		},
		API: apicli.APISpec{
			Action:       "DescribeSandboxToolList",
			RequestType:  "DescribeSandboxToolListRequest",
			ResponseType: "DescribeSandboxToolListResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:   "ToolIds",
				Parser: "common.default_string_array",
				Inputs: []apicli.InputSpec{
					{Name: "tool-ids", Flag: "tool-ids", Usage: "Filter by tool IDs (generated ToolIds flag)", Type: command.FlagStringArray},
				},
			},
			{
				Name:   "Offset",
				Parser: "common.default_int",
				Inputs: []apicli.InputSpec{
					{Name: "offset", Flag: "offset", Usage: "Pagination offset", Type: command.FlagInt},
				},
			},
			{
				Name:   "Limit",
				Parser: "common.default_int",
				Inputs: []apicli.InputSpec{
					{Name: "limit", Flag: "limit", Usage: "Pagination limit", Type: command.FlagInt},
				},
			},
			{
				Name:   "Filters",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "filters", Flag: "filters", Usage: "Additional filters as JSON array, @file, or - for stdin", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
