// Code generated by cobragen; DO NOT EDIT.

package delete

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "apikey.delete",
			Path:         []string{"apikey", "delete"},
			Use:          "delete <key-id>",
			Short:        "Delete an API key",
			Aliases:      []string{"rm", "del"},
			SupportsJSON: true,
			Args: []command.ArgSpec{
				{Name: "key-id", Required: true, Description: "API key ID."},
			},
			Output: command.OutputSpec{
				DataType:    "DeleteAPIKeyResponse",
				Description: "API key delete response.",
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"apikey"}, Use: "apikey", Short: "Manage API keys", Long: "Manage API keys for AGR sandbox access.", Aliases: []string{"ak", "key"}},
		},
		API: apicli.APISpec{
			Action:       "DeleteAPIKey",
			RequestType:  "DeleteAPIKeyRequest",
			ResponseType: "DeleteAPIKeyResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "KeyId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "key-id", Positional: true},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
