// Code generated by cobragen; DO NOT EDIT.

package create

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "tool.create",
			Path:         []string{"tool", "create"},
			Use:          "create",
			Short:        "Create a new sandbox tool",
			Long:         "Create a new sandbox tool template.\n\nTool names must be unique within the current AppId.\n\nFor a minimal code-interpreter tool, provide a unique name, `--tool-type code-interpreter`, and a network configuration such as `{\"NetworkMode\":\"SANDBOX\"}`.",
			Examples:     []string{"tool_name=\"my-tool-$(date +%s)-$$\"", "agr tool create --tool-name \"$tool_name\" --tool-type code-interpreter --network-configuration '{\"NetworkMode\":\"SANDBOX\"}'", "agr tool create --tool-name \"$tool_name\" --tool-type code-interpreter --network-configuration '{\"NetworkMode\":\"SANDBOX\"}' -o json --jq '.Data.ToolId'"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "CreateSandboxToolResponse",
				Description: "Sandbox tool create response.",
				Effects:     []string{"create:tool"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"tool"}, Use: "tool", Short: "Manage sandbox tools", Long: "Manage sandbox tools (templates). Tools define the type and capabilities of sandbox instances.", Aliases: []string{"t"}},
		},
		API: apicli.APISpec{
			Action:       "CreateSandboxTool",
			RequestType:  "CreateSandboxToolRequest",
			ResponseType: "CreateSandboxToolResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "ToolName",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "tool-name", Flag: "tool-name", Shorthand: "n", Usage: "Tool name (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "ToolType",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "tool-type", Flag: "tool-type", Shorthand: "t", Usage: "Tool type (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "NetworkConfiguration",
				Required: true,
				Parser:   "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "network-configuration", Flag: "network-configuration", Usage: "NetworkConfiguration as JSON object, @file, or - for stdin (required)", Format: "{\"NetworkMode\":\"<mode>\",\"VpcConfig\":{\"SubnetIds\":[\"subnet-xxx\"],\"SecurityGroupIds\":[\"sg-xxx\"]}}", Examples: []string{"agr tool create -n my-tool -t code-interpreter --network-configuration '{\"NetworkMode\":\"SANDBOX\"}'", "agr tool create -n my-tool -t code-interpreter --network-configuration '{\"NetworkMode\":\"PUBLIC\"}'", "agr tool create -n my-tool -t custom --network-configuration '{\"NetworkMode\":\"VPC\",\"VpcConfig\":{\"SubnetIds\":[\"subnet-xxx\"],\"SecurityGroupIds\":[\"sg-xxx\"]}}'"}, Values: []string{"SANDBOX: no external network access", "PUBLIC: public internet access", "VPC: VPC network access; requires VpcConfig"}, Type: command.FlagString},
				},
			},
			{
				Name:   "Description",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "description", Flag: "description", Shorthand: "d", Usage: "Tool description", Type: command.FlagString},
				},
			},
			{
				Name:   "DefaultTimeout",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "default-timeout", Flag: "default-timeout", Usage: "Default timeout as accepted by the API, for example 5m, 300s, or 1h", Type: command.FlagString},
				},
			},
			{
				Name:   "Tags",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "tags", Flag: "tags", Usage: "Tags as JSON array, @file, or - for stdin", Format: "[{\"Key\":\"<key>\",\"Value\":\"<value>\"}]", Examples: []string{"agr tool create -n my-tool -t code-interpreter --network-configuration '{\"NetworkMode\":\"SANDBOX\"}' --tags '[{\"Key\":\"team\",\"Value\":\"platform\"},{\"Key\":\"env\",\"Value\":\"staging\"}]'"}, Type: command.FlagString},
				},
			},
			{
				Name:   "ClientToken",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "client-token", Flag: "client-token", Usage: "Client token for duplicate creation protection", Type: command.FlagString},
				},
			},
			{
				Name:   "RoleArn",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "role-arn", Flag: "role-arn", Usage: "Role ARN for COS access", Type: command.FlagString},
				},
			},
			{
				Name:   "StorageMounts",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "storage-mounts", Flag: "storage-mounts", Usage: "StorageMounts as JSON array, @file, or - for stdin", Format: "[{\"Name\":\"<name>\",\"MountPath\":\"<path>\",\"ReadOnly\":false,\"StorageSource\":{\"Cos\":{...}}}]", Examples: []string{"agr tool create -n my-tool -t custom --network-configuration '{\"NetworkMode\":\"PUBLIC\"}' --role-arn qcs::cam::uin/100000:roleName/my-role --storage-mounts '[{\"Name\":\"data\",\"MountPath\":\"/data\",\"StorageSource\":{\"Cos\":{\"Endpoint\":\"cos.ap-guangzhou.myqcloud.com\",\"BucketName\":\"my-bucket\",\"BucketPath\":\"/workspace\"}}}]'"}, Values: []string{"Cos: Tencent Cloud Object Storage source", "Image: container image volume source", "Cfs: Cloud File Storage source"}, Type: command.FlagString},
				},
			},
			{
				Name:   "CustomConfiguration",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "custom-configuration", Flag: "custom-configuration", Usage: "CustomConfiguration JSON object, @file, or - for stdin", Format: "{\"Image\":\"<registry>/<image>:<tag>\",\"ImageRegistryType\":\"personal\",\"Command\":[\"/bin/sh\"],\"Args\":[\"-c\",\"sleep 3600\"],\"Env\":[{\"Name\":\"KEY\",\"Value\":\"VAL\"}],\"Ports\":[{\"Name\":\"app\",\"Port\":8080,\"Protocol\":\"TCP\"}],\"Resources\":{\"CPU\":\"2\",\"Memory\":\"4Gi\"}}", Examples: []string{"agr tool create -n my-tool -t custom --network-configuration '{\"NetworkMode\":\"PUBLIC\"}' --custom-configuration '{\"Image\":\"ubuntu:22.04\",\"ImageRegistryType\":\"personal\",\"Resources\":{\"CPU\":\"2\",\"Memory\":\"4Gi\"}}'"}, Type: command.FlagString},
				},
			},
			{
				Name:   "LogConfiguration",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "log-configuration", Flag: "log-configuration", Usage: "LogConfiguration JSON object, @file, or - for stdin", Format: "{\"CLSConfig\":{\"TopicId\":\"<cls-topic-id>\"}}", Examples: []string{"agr tool create -n my-tool -t code-interpreter --network-configuration '{\"NetworkMode\":\"SANDBOX\"}' --log-configuration '{\"CLSConfig\":{\"TopicId\":\"xxxxx-xxxx-xxxx\"}}'"}, Type: command.FlagString},
				},
			},
			{
				Name:   "Persistent",
				Parser: "common.default_bool",
				Inputs: []apicli.InputSpec{
					{Name: "persistent", Flag: "persistent", Usage: "Whether the sandbox tool creates persistent sandboxes", Type: command.FlagBool},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
