// Code generated by cobragen; DO NOT EDIT.

package create

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "tool.create",
			Path:         []string{"tool", "create"},
			Use:          "create",
			Short:        "Create a new sandbox tool",
			Long:         "Create a new sandbox tool template.\n\nTool names must be unique within the current AppId.\n\nFor a minimal code-interpreter tool, provide a unique name, `--tool-type code-interpreter`, and a network configuration such as `{\"NetworkMode\":\"SANDBOX\"}`.",
			Examples:     []string{"tool_name=\"my-tool-$(date +%s)-$$\"", "agr tool create --tool-name \"$tool_name\" --tool-type code-interpreter --network-configuration '{\"NetworkMode\":\"SANDBOX\"}'", "agr tool create --tool-name \"$tool_name\" --tool-type code-interpreter --network-configuration '{\"NetworkMode\":\"SANDBOX\"}' -o json --jq '.ToolId'"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "CreateSandboxToolResponse",
				Description: "Sandbox tool create response.",
				Effects:     []string{"create:tool"},
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"tool"}, Use: "tool", Short: "Manage sandbox tools", Long: "Manage sandbox tools (templates). Tools define the type and capabilities of sandbox instances.", Aliases: []string{"t"}},
		},
		API: apicli.APISpec{
			Action:       "CreateSandboxTool",
			RequestType:  "CreateSandboxToolRequest",
			ResponseType: "CreateSandboxToolResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "ToolName",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "tool-name", Flag: "tool-name", Shorthand: "n", Usage: "Tool name (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "ToolType",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "tool-type", Flag: "tool-type", Shorthand: "t", Usage: "Tool type (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "NetworkConfiguration",
				Required: true,
				Parser:   "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "network-configuration", Flag: "network-configuration", Usage: "NetworkConfiguration as JSON object, @file, or - for stdin (required)", Type: command.FlagString},
				},
			},
			{
				Name:   "Description",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "description", Flag: "description", Shorthand: "d", Usage: "Tool description", Type: command.FlagString},
				},
			},
			{
				Name:   "DefaultTimeout",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "default-timeout", Flag: "default-timeout", Usage: "Default timeout as accepted by the API, for example 5m, 300s, or 1h", Type: command.FlagString},
				},
			},
			{
				Name:   "Tags",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "tags", Flag: "tags", Usage: "Tags as JSON array, @file, or - for stdin", Type: command.FlagString},
				},
			},
			{
				Name:   "ClientToken",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "client-token", Flag: "client-token", Usage: "Client token for duplicate creation protection", Type: command.FlagString},
				},
			},
			{
				Name:   "RoleArn",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "role-arn", Flag: "role-arn", Usage: "Role ARN for COS access", Type: command.FlagString},
				},
			},
			{
				Name:   "StorageMounts",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "storage-mounts", Flag: "storage-mounts", Usage: "StorageMounts as JSON array, @file, or - for stdin", Type: command.FlagString},
				},
			},
			{
				Name:   "CustomConfiguration",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "custom-configuration", Flag: "custom-configuration", Usage: "CustomConfiguration JSON object, @file, or - for stdin", Type: command.FlagString},
				},
			},
			{
				Name:   "LogConfiguration",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "log-configuration", Flag: "log-configuration", Usage: "LogConfiguration JSON object, @file, or - for stdin", Type: command.FlagString},
				},
			},
			{
				Name:   "Persistent",
				Parser: "common.default_bool",
				Inputs: []apicli.InputSpec{
					{Name: "persistent", Flag: "persistent", Usage: "Whether the sandbox tool creates persistent sandboxes", Type: command.FlagBool},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
