// Code generated by cobragen; DO NOT EDIT.

package delete

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "tool.delete",
			Path:         []string{"tool", "delete"},
			Use:          "delete <tool-id> [tool-id...]",
			Short:        "Delete sandbox tools",
			Aliases:      []string{"rm", "del"},
			SupportsJSON: true,
			Args: []command.ArgSpec{
				{Name: "tool-id", Required: true, Repeatable: true, Description: "Sandbox tool ID."},
			},
			Output: command.OutputSpec{
				DataType:    "DeleteSandboxToolResponse",
				Description: "Sandbox tool delete response.",
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"tool"}, Use: "tool", Short: "Manage sandbox tools", Long: "Manage sandbox tools (templates). Tools define the type and capabilities of sandbox instances.", Aliases: []string{"t"}},
		},
		API: apicli.APISpec{
			Action:       "DeleteSandboxTool",
			RequestType:  "DeleteSandboxToolRequest",
			ResponseType: "DeleteSandboxToolResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "ToolId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "tool-id", Positional: true},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
