// Command docgen renders agr's command tree to markdown / man pages.
//
// Per NextPlan §9.5 there is no user-facing `agr docs ...` surface;
// the binary itself produces only --help. This maintainer entry
// point is invoked manually or by CI to verify the cobra tree can be
// rendered, without committing the output into the repository.
//
// Usage:
//
//	go run ./cmd/internal/docgen markdown --dir docs
//	go run ./cmd/internal/docgen man      --dir man
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra/doc"

	cli "github.com/TencentCloudAgentRuntime/ags-cli/internal/cli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/commands"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "usage: docgen <markdown|man> [--dir <path>]")
		os.Exit(2)
	}
	sub := os.Args[1]
	args := os.Args[2:]

	fs := flag.NewFlagSet(sub, flag.ContinueOnError)
	dir := fs.String("dir", defaultDir(sub), "output directory")
	if err := fs.Parse(args); err != nil {
		os.Exit(2)
	}
	if *dir == "" {
		fmt.Fprintln(os.Stderr, "docgen: --dir is required")
		os.Exit(2)
	}
	if err := os.MkdirAll(*dir, 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "docgen: %v\n", err)
		os.Exit(1)
	}

	var err error
	switch sub {
	case "markdown", "md":
		err = renderMarkdown(*dir)
	case "man":
		err = renderMan(*dir)
	default:
		fmt.Fprintf(os.Stderr, "docgen: unknown subcommand %q (allowed: markdown, man)\n", sub)
		os.Exit(2)
	}
	if err != nil {
		fmt.Fprintf(os.Stderr, "docgen: %v\n", err)
		os.Exit(1)
	}
}

func defaultDir(sub string) string {
	switch sub {
	case "markdown", "md":
		return "docs"
	case "man":
		return "man"
	}
	return ""
}

func renderMarkdown(dir string) error {
	root := cli.RootCmd()
	if err := attachCommands(); err != nil {
		return err
	}
	if err := doc.GenMarkdownTree(root, dir); err != nil {
		return fmt.Errorf("render markdown: %w", err)
	}
	files, _ := filepath.Glob(filepath.Join(dir, "*.md"))
	for _, f := range files {
		if err := normalizeMarkdown(f); err != nil {
			return err
		}
	}
	fmt.Printf("Generated %d markdown files in %s/\n", len(files), dir)
	return nil
}

func renderMan(dir string) error {
	root := cli.RootCmd()
	if err := attachCommands(); err != nil {
		return err
	}
	header := &doc.GenManHeader{
		Title: "AGR", Section: "1", Source: "AGR CLI", Manual: "AGR Manual",
	}
	if err := doc.GenManTree(root, header, dir); err != nil {
		return fmt.Errorf("render man: %w", err)
	}
	files, _ := filepath.Glob(filepath.Join(dir, "*.1"))
	fmt.Printf("Generated %d man pages in %s/\n", len(files), dir)
	return nil
}

func attachCommands() error {
	registry, err := commands.Registry()
	if err != nil {
		return err
	}
	return cli.AttachCommandRegistry(registry)
}

// normalizeMarkdown strips the build-time comment line that cobra/doc
// inserts so two runs at different timestamps still produce identical
// output.
func normalizeMarkdown(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}
	lines := strings.Split(string(data), "\n")
	for i, line := range lines {
		if strings.HasPrefix(line, "###### Auto generated by spf13/cobra") {
			lines[i] = "###### Auto generated by spf13/cobra"
		}
	}
	if err := os.WriteFile(path, []byte(strings.Join(lines, "\n")), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
