// Code generated by cobragen; DO NOT EDIT.

package resume

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "instance.resume",
			Path:         []string{"instance", "resume"},
			Use:          "resume <instance-id>",
			Short:        "Resume instance",
			SupportsJSON: true,
			Args: []command.ArgSpec{
				{Name: "instance-id", Required: true, Description: "Sandbox instance ID."},
			},
			Output: command.OutputSpec{
				DataType:    "ResumeSandboxInstanceResponse",
				Description: "Instance resume response.",
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"instance"}, Use: "instance", Short: "Manage sandbox instances", Long: "Manage sandbox instances and related data-plane workflows.", Aliases: []string{"i"}},
		},
		API: apicli.APISpec{
			Action:       "ResumeSandboxInstance",
			RequestType:  "ResumeSandboxInstanceRequest",
			ResponseType: "ResumeSandboxInstanceResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "InstanceId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "instance-id", Positional: true},
				},
			},
			{
				Name:   "Timeout",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "timeout", Flag: "timeout", Usage: "超时时间，超过这个时间就自动回收实例。支持格式：5m、300s、1h 等，默认 5m。最小 30s，最大 24h", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
