// Code generated by cobragen; DO NOT EDIT.

package pause

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "instance.pause",
			Path:         []string{"instance", "pause"},
			Use:          "pause <instance-id>",
			Short:        "Pause instance",
			SupportsJSON: true,
			Args: []command.ArgSpec{
				{Name: "instance-id", Required: true, Description: "Sandbox instance ID."},
			},
			Output: command.OutputSpec{
				DataType:    "PauseSandboxInstanceResponse",
				Description: "Instance pause response.",
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"instance"}, Use: "instance", Short: "Manage sandbox instances", Long: "Manage sandbox instances and related data-plane workflows.", Aliases: []string{"i"}},
		},
		API: apicli.APISpec{
			Action:       "PauseSandboxInstance",
			RequestType:  "PauseSandboxInstanceRequest",
			ResponseType: "PauseSandboxInstanceResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "InstanceId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "instance-id", Positional: true},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
