// Code generated by cobragen; DO NOT EDIT.

package create

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "instance.create",
			Path:         []string{"instance", "create"},
			Use:          "create",
			Short:        "Create a new sandbox instance",
			Long:         "Create a new sandbox instance from a tool template.\n\nThe referenced tool must already exist. Create one first with `agr tool create`, or pass an existing --tool-id.\n\nUse --tool-name/-t for tool name or --tool-id for tool ID.\n\nComplex API fields such as --mount-options, --metadata, and --custom-configuration accept JSON, @file, or - for stdin.\n\nAuth mode (--auth-mode):\n  DEFAULT  Use backend default (currently TOKEN)\n  TOKEN    All ports require X-Access-Token\n  PUBLIC   envd management port (49983) requires token; other ports open\n  NONE     No authentication on any port",
			Examples:     []string{"agr instance create --tool-id sdt-xxxx", "agr instance create --tool-name my-tool", "agr instance create -t my-tool --timeout 5m", "agr instance create --tool-id sdt-xxxx --mount-options '[{\"Name\":\"data\",\"MountPath\":\"/workspace\"}]'", "agr instance create -t my-tool --auth-mode NONE"},
			Aliases:      []string{"c"},
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "StartSandboxInstanceResponse",
				Description: "Instance create response.",
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"instance"}, Use: "instance", Short: "Manage sandbox instances", Long: "Manage sandbox instances and related data-plane workflows.", Aliases: []string{"i"}},
		},
		API: apicli.APISpec{
			Action:       "StartSandboxInstance",
			RequestType:  "StartSandboxInstanceRequest",
			ResponseType: "StartSandboxInstanceResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:   "ToolId",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "tool-id", Flag: "tool-id", Usage: "Tool ID", Type: command.FlagString},
				},
			},
			{
				Name:   "ToolName",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "tool-name", Flag: "tool-name", Shorthand: "t", Usage: "Tool name", Type: command.FlagString},
				},
			},
			{
				Name:   "Timeout",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "timeout", Flag: "timeout", Usage: "Instance timeout as accepted by the API, for example 5m, 300s, or 1h", Type: command.FlagString},
				},
			},
			{
				Name:   "ClientToken",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "client-token", Flag: "client-token", Usage: "Client token for duplicate creation protection", Type: command.FlagString},
				},
			},
			{
				Name:   "MountOptions",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "mount-options", Flag: "mount-options", Usage: "MountOptions as JSON array, @file, or - for stdin", Format: "[{\"Name\":\"<name>\",\"MountPath\":\"<path>\"}]", Examples: []string{"agr instance create --tool-id sdt-xxxx --mount-options '[{\"Name\":\"data\",\"MountPath\":\"/workspace\"}]'", "agr instance create --tool-id sdt-xxxx --mount-options @mounts.json"}, Type: command.FlagString},
				},
			},
			{
				Name:   "CustomConfiguration",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "custom-configuration", Flag: "custom-configuration", Usage: "CustomConfiguration JSON object, @file, or - for stdin", Type: command.FlagString},
				},
			},
			{
				Name:   "AuthMode",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "auth-mode", Flag: "auth-mode", Usage: "Auth mode: DEFAULT, TOKEN, NONE, PUBLIC", Values: []string{"DEFAULT", "TOKEN", "NONE", "PUBLIC"}, Type: command.FlagString},
				},
			},
			{
				Name:   "Metadata",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "metadata", Flag: "metadata", Usage: "Metadata as JSON array, @file, or - for stdin", Format: "[{\"Key\":\"<key>\",\"Value\":\"<value>\"}]", Examples: []string{"agr instance create --tool-id sdt-xxxx --metadata '[{\"Key\":\"env\",\"Value\":\"test\"}]'"}, Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
