// Code generated by cobragen; DO NOT EDIT.

package create

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "pre-cache-image-task.create",
			Path:         []string{"pre-cache-image-task", "create"},
			Use:          "create --image <image> --image-registry-type <type>",
			Short:        "Create an image pre-cache task",
			SupportsJSON: true,
			Output: command.OutputSpec{
				DataType:    "CreatePreCacheImageTaskResponse",
				Description: "Image pre-cache task create response.",
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"pre-cache-image-task"}, Use: "pre-cache-image-task", Short: "Manage image pre-cache tasks", Aliases: []string{"pre_cache_image_task"}},
		},
		API: apicli.APISpec{
			Action:       "CreatePreCacheImageTask",
			RequestType:  "CreatePreCacheImageTaskRequest",
			ResponseType: "CreatePreCacheImageTaskResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "Image",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "image", Flag: "image", Usage: "Image reference (required)", Type: command.FlagString},
				},
			},
			{
				Name:     "ImageRegistryType",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "image-registry-type", Flag: "image-registry-type", Usage: "Image registry type: enterprise or personal (required)", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
