// Code generated by cobragen; DO NOT EDIT.

package delete

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "instance.delete",
			Path:         []string{"instance", "delete"},
			Use:          "delete <instance-id> [instance-id...]",
			Short:        "Delete instances",
			Long:         "Delete one or more sandbox instances. This operation executes immediately and does not prompt for confirmation.",
			Aliases:      []string{"rm", "del"},
			SupportsJSON: true,
			Args: []command.ArgSpec{
				{Name: "instance-id", Required: true, Repeatable: true, Description: "Sandbox instance ID."},
			},
			Output: command.OutputSpec{
				DataType:    "StopSandboxInstanceResponse",
				Description: "Instance stop response.",
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"instance"}, Use: "instance", Short: "Manage sandbox instances", Long: "Manage sandbox instances and related data-plane workflows.", Aliases: []string{"i"}},
		},
		API: apicli.APISpec{
			Action:       "StopSandboxInstance",
			RequestType:  "StopSandboxInstanceRequest",
			ResponseType: "StopSandboxInstanceResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "InstanceId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "instance-id", Positional: true},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
