// Code generated by cobragen; DO NOT EDIT.

package update

import (
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/command"
)

func APIDescriptor() apicli.APIDescriptor {
	return apicli.APIDescriptor{
		Spec: command.Spec{
			ID:           "instance.update",
			Path:         []string{"instance", "update"},
			Use:          "update <instance-id>",
			Short:        "Update instance",
			SupportsJSON: true,
			Args: []command.ArgSpec{
				{Name: "instance-id", Required: true, Description: "Sandbox instance ID."},
			},
			Output: command.OutputSpec{
				DataType:    "UpdateSandboxInstanceResponse",
				Description: "Instance update response.",
			},
		},
		Groups: []command.GroupSpec{
			{Path: []string{"instance"}, Use: "instance", Short: "Manage sandbox instances", Long: "Manage sandbox instances and related data-plane workflows.", Aliases: []string{"i"}},
		},
		API: apicli.APISpec{
			Action:       "UpdateSandboxInstance",
			RequestType:  "UpdateSandboxInstanceRequest",
			ResponseType: "UpdateSandboxInstanceResponse",
		},
		Fields: []apicli.FieldSpec{
			{
				Name:     "InstanceId",
				Required: true,
				Parser:   "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "instance-id", Positional: true},
				},
			},
			{
				Name:   "Timeout",
				Parser: "common.default_string",
				Inputs: []apicli.InputSpec{
					{Name: "timeout", Flag: "timeout", Usage: "New timeout such as 10m or 300s", Type: command.FlagString},
				},
			},
			{
				Name:   "Metadata",
				Parser: "common.default_json",
				Inputs: []apicli.InputSpec{
					{Name: "metadata", Flag: "metadata", Usage: "Metadata as JSON array, @file, or - for stdin", Type: command.FlagString},
				},
			},
		},
	}
}

func GeneratedModule() command.Module {
	return apicli.NewModule(APIDescriptor())
}
