package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli/parsers"
	"github.com/TencentCloudAgentRuntime/ags-cli/internal/apimeta"
)

const (
	apiService = "ags"
	apiVersion = "v20250920"
)

type commandModel struct {
	Action   string
	Command  string
	Request  string
	Response string
	Parts    []string
	Use      string
	Aliases  []string
	Args     string
	Hook     string
	Short    string
	Long     string
	Examples []string
	Package  string
	Dir      string
	Fields   []fieldModel
}

type fieldModel struct {
	Name       string
	Type       string
	Member     string
	Required   bool
	Parser     string
	Positional bool
	Excluded   bool
	Inputs     []inputModel
}

type inputModel struct {
	Field     string
	Flag      string
	GoType    string
	CobraType string
	Default   string
	Shorthand string
	Usage     string
	Format    string
	Examples  []string
	Values    []string
	Aliases   []string
}

type argModel struct {
	Name        string
	Description string
	Required    bool
	Repeatable  bool
}

type groupModel struct {
	Path    []string
	Use     string
	Short   string
	Long    string
	Aliases []string
}

func main() {
	apiDir := flag.String("api", filepath.Join("api", apiService, apiVersion), "directory containing api.json, mapping.yaml and help.json")
	check := flag.Bool("check", false, "fail if generated files are stale")
	flag.Parse()
	args := flag.Args()
	if len(args) > 0 && args[0] == "check" {
		*check = true
	}
	if err := run(*apiDir, *check); err != nil {
		fmt.Fprintf(os.Stderr, "cobragen: %v\n", err)
		os.Exit(1)
	}
}

func run(apiDir string, check bool) error {
	spec, err := apimeta.LoadSpec(filepath.Join(apiDir, "api.json"))
	if err != nil {
		return err
	}
	mapping, err := apimeta.LoadMapping(filepath.Join(apiDir, "mapping.yaml"))
	if err != nil {
		return err
	}
	help, err := apimeta.LoadHelp(filepath.Join(apiDir, "help.json"))
	if err != nil {
		return err
	}
	if err := validate(spec, mapping); err != nil {
		return err
	}
	files, err := renderAll(spec, mapping, help)
	if err != nil {
		return err
	}
	if check {
		var stale []string
		for path, want := range files {
			got, err := os.ReadFile(path)
			if err != nil || !bytes.Equal(got, want) {
				stale = append(stale, path)
			}
		}
		sort.Strings(stale)
		if len(stale) > 0 {
			for _, path := range stale {
				fmt.Fprintf(os.Stderr, "stale: %s\n", path)
			}
			return fmt.Errorf("generated files are out of date; rerun go run ./cmd/internal/cobragen")
		}
		fmt.Println("cobragen outputs are up to date.")
		return nil
	}
	for path, data := range files {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, data, 0o644); err != nil {
			return err
		}
		fmt.Println("wrote", path)
	}
	return nil
}

func validate(spec *apimeta.Spec, mapping *apimeta.Mapping) error {
	var errs []string
	for _, issue := range mapping.Validate(spec) {
		if issue.IsError() {
			errs = append(errs, issue.String())
		}
	}
	for _, name := range mapping.MappedActionNames() {
		a := mapping.Actions[name]
		for field, fm := range a.Fields {
			if fm.Parser != "" && !parsers.Exists(fm.Parser) {
				errs = append(errs, fmt.Sprintf("[%s] %s field=%s: unknown parser %q", "UNKNOWN_PARSER", name, field, fm.Parser))
			}
		}
	}
	if len(errs) > 0 {
		sort.Strings(errs)
		return fmt.Errorf("validation failed:\n  - %s", strings.Join(errs, "\n  - "))
	}
	return nil
}

func renderAll(spec *apimeta.Spec, mapping *apimeta.Mapping, help *apimeta.Help) (map[string][]byte, error) {
	files := map[string][]byte{}
	model, err := renderGeneratedModel(spec, mapping, help)
	if err != nil {
		return nil, err
	}
	files[filepath.Join("internal", "apimeta", "generated_model.go")] = model

	commands := buildCommands(spec, mapping, help)
	registry, err := renderCommandRegistry(commands)
	if err != nil {
		return nil, err
	}
	files[filepath.Join("internal", "commands", "registry.generated.go")] = registry
	for _, cmd := range commands {
		data, err := renderAPICommand(cmd)
		if err != nil {
			return nil, err
		}
		cleanParts := make([]string, len(cmd.Parts))
		for i, p := range cmd.Parts {
			cleanParts[i] = strings.ReplaceAll(p, "-", "")
		}
		files[filepath.Join("internal", "commands", filepath.Join(cleanParts...), "api.generated.go")] = data
	}
	return files, nil
}

func renderGeneratedModel(spec *apimeta.Spec, mapping *apimeta.Mapping, help *apimeta.Help) ([]byte, error) {
	cat := apimeta.BuildCatalog(spec, mapping)
	catJSON, err := json.Marshal(cat)
	if err != nil {
		return nil, err
	}
	helpJSON, err := json.Marshal(help)
	if err != nil {
		return nil, err
	}
	src := fmt.Sprintf("// Code generated by cobragen; DO NOT EDIT.\n\npackage apimeta\n\nvar generatedCatalogJSON = []byte(%s)\n\nvar generatedHelpJSON = []byte(%s)\n", strconv.Quote(string(catJSON)), strconv.Quote(string(helpJSON)))
	return gofmt("internal/apimeta/generated_model.go", []byte(src))
}

func buildCommands(spec *apimeta.Spec, mapping *apimeta.Mapping, help *apimeta.Help) []commandModel {
	var out []commandModel
	for _, action := range mapping.MappedActionNames() {
		a := mapping.Actions[action]
		parts := strings.Split(a.Command, ".")
		if len(parts) < 2 {
			continue
		}
		obj := spec.Object(a.Request)
		cmd := commandModel{
			Action:   action,
			Command:  a.Command,
			Request:  a.Request,
			Response: a.Response,
			Parts:    parts,
			Use:      useForCommand(a.Command),
			Aliases:  aliasesForCommand(a.Command),
			Args:     argsForCommand(a.Command),
			Hook:     hookForCommand(a.Command),
			Short:    commandShortFromHelp(help, a.Command),
			Long:     commandLongFromHelp(help, a.Command),
			Examples: commandExamplesFromHelp(help, a.Command),
			Package:  packageForCommand(parts),
			Dir:      dirForCommand(parts),
		}
		if obj != nil {
			for _, m := range obj.Members {
				if m.Disabled {
					continue
				}
				fm := a.Fields[m.Name]
				parser := parserForField(m, fm)
				field := fieldModel{
					Name:       m.Name,
					Type:       m.Type,
					Member:     m.Member,
					Required:   m.Required && (fm == nil || !fm.Excluded),
					Parser:     parser,
					Positional: fm != nil && fm.Positional,
					Excluded:   fm != nil && fm.Excluded,
				}
				for _, in := range inputsFor(m, fm) {
					if field.Excluded {
						continue
					}
					ih := inputHelp(help, a.Command, m.Name, in.Flag, strip(m.Document))
					if field.Required && !strings.Contains(strings.ToLower(ih.Usage), "required") {
						ih.Usage = strings.TrimSpace(ih.Usage)
						if ih.Usage == "" {
							ih.Usage = in.Flag
						}
						ih.Usage += " (required)"
					}
					field.Inputs = append(field.Inputs, inputModel{
						Field:     m.Name,
						Flag:      in.Flag,
						GoType:    goTypeForInput(in.Type),
						CobraType: cobraTypeForInput(in.Type),
						Default:   in.Default,
						Shorthand: in.Shorthand,
						Usage:     ih.Usage,
						Format:    ih.Format,
						Examples:  append([]string(nil), ih.Examples...),
						Values:    append([]string(nil), ih.Values...),
						Aliases:   append([]string(nil), in.Aliases...),
					})
				}
				cmd.Fields = append(cmd.Fields, field)
			}
		}
		out = append(out, cmd)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Command < out[j].Command })
	return out
}

func renderAPICommand(cmd commandModel) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by cobragen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", cmd.Package)
	b.WriteString("import (\n")
	b.WriteString("\t\"github.com/TencentCloudAgentRuntime/ags-cli/internal/apicli\"\n")
	b.WriteString("\t\"github.com/TencentCloudAgentRuntime/ags-cli/internal/command\"\n")
	b.WriteString(")\n\n")
	b.WriteString("func APIDescriptor() apicli.APIDescriptor {\n")
	b.WriteString("\treturn apicli.APIDescriptor{\n")
	b.WriteString("\t\tSpec: command.Spec{\n")
	fmt.Fprintf(&b, "\t\t\tID: %s,\n", quote(cmd.Command))
	fmt.Fprintf(&b, "\t\t\tPath: []string{%s},\n", quotedList(cmd.Parts))
	fmt.Fprintf(&b, "\t\t\tUse: %s,\n", quote(cmd.Use))
	fmt.Fprintf(&b, "\t\t\tShort: %s,\n", quote(cmd.Short))
	if cmd.Long != "" {
		fmt.Fprintf(&b, "\t\t\tLong: %s,\n", quote(cmd.Long))
	}
	if len(cmd.Examples) > 0 {
		fmt.Fprintf(&b, "\t\t\tExamples: []string{%s},\n", quotedList(cmd.Examples))
	}
	if len(cmd.Aliases) > 0 {
		fmt.Fprintf(&b, "\t\t\tAliases: []string{%s},\n", quotedList(cmd.Aliases))
	}
	b.WriteString("\t\t\tSupportsJSON: true,\n")
	if args := argSpecs(cmd); len(args) > 0 {
		b.WriteString("\t\t\tArgs: []command.ArgSpec{\n")
		for _, arg := range args {
			b.WriteString("\t\t\t\t{")
			fmt.Fprintf(&b, "Name: %s", quote(arg.Name))
			if arg.Required {
				b.WriteString(", Required: true")
			}
			if arg.Repeatable {
				b.WriteString(", Repeatable: true")
			}
			if arg.Description != "" {
				fmt.Fprintf(&b, ", Description: %s", quote(arg.Description))
			}
			b.WriteString("},\n")
		}
		b.WriteString("\t\t\t},\n")
	}
	b.WriteString("\t\t\tOutput: command.OutputSpec{\n")
	fmt.Fprintf(&b, "\t\t\t\tDataType: %s,\n", quote(cmd.Response))
	fmt.Fprintf(&b, "\t\t\t\tDescription: %s,\n", quote(outputDescription(cmd)))
	if effects := outputEffects(cmd); len(effects) > 0 {
		fmt.Fprintf(&b, "\t\t\t\tEffects: []string{%s},\n", quotedList(effects))
	}
	b.WriteString("\t\t\t},\n")
	b.WriteString("\t\t},\n")
	b.WriteString("\t\tGroups: []command.GroupSpec{\n")
	for _, group := range groupSpecsForCommand(cmd.Parts) {
		b.WriteString("\t\t\t{")
		fmt.Fprintf(&b, "Path: []string{%s}", quotedList(group.Path))
		fmt.Fprintf(&b, ", Use: %s", quote(group.Use))
		fmt.Fprintf(&b, ", Short: %s", quote(group.Short))
		if group.Long != "" {
			fmt.Fprintf(&b, ", Long: %s", quote(group.Long))
		}
		if len(group.Aliases) > 0 {
			fmt.Fprintf(&b, ", Aliases: []string{%s}", quotedList(group.Aliases))
		}
		b.WriteString("},\n")
	}
	b.WriteString("\t\t},\n")
	b.WriteString("\t\tAPI: apicli.APISpec{\n")
	fmt.Fprintf(&b, "\t\t\tAction: %s,\n", quote(cmd.Action))
	fmt.Fprintf(&b, "\t\t\tRequestType: %s,\n", quote(cmd.Request))
	fmt.Fprintf(&b, "\t\t\tResponseType: %s,\n", quote(cmd.Response))
	b.WriteString("\t\t},\n")
	if len(cmd.Fields) > 0 {
		b.WriteString("\t\tFields: []apicli.FieldSpec{\n")
		for _, field := range cmd.Fields {
			if field.Excluded {
				continue
			}
			b.WriteString("\t\t\t{\n")
			fmt.Fprintf(&b, "\t\t\t\tName: %s,\n", quote(field.Name))
			if field.Required {
				b.WriteString("\t\t\t\tRequired: true,\n")
			}
			fmt.Fprintf(&b, "\t\t\t\tParser: %s,\n", quote(field.Parser))
			if len(field.Inputs) > 0 {
				b.WriteString("\t\t\t\tInputs: []apicli.InputSpec{\n")
				for _, input := range field.Inputs {
					b.WriteString("\t\t\t\t\t{")
					fmt.Fprintf(&b, "Name: %s", quote(input.Flag))
					if input.Flag != "" && !isPositionalInput(field, input) {
						fmt.Fprintf(&b, ", Flag: %s", quote(input.Flag))
					}
					if input.Shorthand != "" {
						fmt.Fprintf(&b, ", Shorthand: %s", quote(input.Shorthand))
					}
					if len(input.Aliases) > 0 {
						fmt.Fprintf(&b, ", Aliases: []string{%s}", quotedList(input.Aliases))
					}
					if input.Usage != "" && !isPositionalInput(field, input) {
						fmt.Fprintf(&b, ", Usage: %s", quote(input.Usage))
					}
					if input.Format != "" && !isPositionalInput(field, input) {
						fmt.Fprintf(&b, ", Format: %s", quote(input.Format))
					}
					if len(input.Examples) > 0 && !isPositionalInput(field, input) {
						fmt.Fprintf(&b, ", Examples: []string{%s}", quotedList(input.Examples))
					}
					if len(input.Values) > 0 && !isPositionalInput(field, input) {
						fmt.Fprintf(&b, ", Values: []string{%s}", quotedList(input.Values))
					}
					if !isPositionalInput(field, input) {
						fmt.Fprintf(&b, ", Type: %s", commandFlagType(input.CobraType))
						if input.Default != "" {
							fmt.Fprintf(&b, ", Default: %s", defaultLiteral(input))
						}
					} else {
						b.WriteString(", Positional: true")
					}
					b.WriteString("},\n")
				}
				b.WriteString("\t\t\t\t},\n")
			}
			b.WriteString("\t\t\t},\n")
		}
		b.WriteString("\t\t},\n")
	} else {
		b.WriteString("\t\tDisableRequestFlag: true,\n")
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")
	b.WriteString("func GeneratedModule() command.Module {\n")
	b.WriteString("\treturn apicli.NewModule(APIDescriptor())\n")
	b.WriteString("}\n")
	return gofmt(filepath.Join("internal", "commands", filepath.Join(cmd.Parts...), "api.generated.go"), []byte(b.String()))
}

func argSpecs(cmd commandModel) []argModel {
	var args []argModel
	for _, field := range cmd.Fields {
		if !field.Positional || field.Excluded {
			continue
		}
		name := apimeta.KebabCase(field.Name)
		desc := positionalDescription(name)
		args = append(args, argModel{Name: name, Description: desc, Required: true})
	}
	if strings.HasSuffix(cmd.Command, ".delete") && len(args) == 1 {
		args[0].Repeatable = cmd.Command == "instance.delete" || cmd.Command == "tool.delete"
	}
	return args
}

func positionalDescription(name string) string {
	switch name {
	case "instance-id":
		return "Sandbox instance ID."
	case "tool-id":
		return "Sandbox tool ID."
	case "key-id":
		return "API key ID."
	case "image-digest":
		return "Image digest."
	default:
		return strings.TrimSpace(exported(name) + ".")
	}
}

func groupSpecsForCommand(parts []string) []groupModel {
	if len(parts) < 2 {
		return nil
	}
	var groups []groupModel
	first := parts[0]
	groups = append(groups, groupModel{
		Path:    []string{first},
		Use:     first,
		Short:   groupShort(first),
		Long:    groupLong(first),
		Aliases: aliasesForGroup(first),
	})
	for i := 1; i < len(parts)-1; i++ {
		path := append([]string(nil), parts[:i+1]...)
		groups = append(groups, groupModel{
			Path:  path,
			Use:   parts[i],
			Short: subgroupShort(first, parts[i]),
		})
	}
	return groups
}

func outputDescription(cmd commandModel) string {
	switch cmd.Command {
	case "apikey.create":
		return "API key create response."
	case "apikey.delete":
		return "API key delete response."
	case "apikey.list":
		return "API key list response."
	case "pre-cache-image-task.create":
		return "Image pre-cache task create response."
	case "pre-cache-image-task.get":
		return "Image pre-cache task response."
	case "instance.create":
		return "Instance create response."
	case "instance.delete":
		return "Instance stop response."
	case "instance.list":
		return "Instance list response."
	case "instance.pause":
		return "Instance pause response."
	case "instance.resume":
		return "Instance resume response."
	case "instance.update":
		return "Instance update response."
	case "tool.create":
		return "Sandbox tool create response."
	case "tool.delete":
		return "Sandbox tool delete response."
	case "tool.list":
		return "Sandbox tool list response."
	case "tool.update":
		return "Sandbox tool update response."
	default:
		return cmd.Response + " response."
	}
}

func outputEffects(cmd commandModel) []string {
	if cmd.Command == "tool.create" {
		return []string{"create:tool"}
	}
	return nil
}

func isPositionalInput(field fieldModel, input inputModel) bool {
	return field.Positional
}

func commandFlagType(cobraType string) string {
	switch cobraType {
	case "bool":
		return "command.FlagBool"
	case "int":
		return "command.FlagInt"
	case "stringArray":
		return "command.FlagStringArray"
	default:
		return "command.FlagString"
	}
}

func defaultLiteral(input inputModel) string {
	switch input.CobraType {
	case "bool":
		return boolDefault(input.Default)
	case "int":
		return intDefault(input.Default)
	default:
		return quote(input.Default)
	}
}

func quotedList(items []string) string {
	var out []string
	for _, item := range items {
		out = append(out, quote(item))
	}
	return strings.Join(out, ", ")
}

type registryModule struct {
	ID     string
	Alias  string
	Path   string
	Symbol string
}

func renderCommandRegistry(commands []commandModel) ([]byte, error) {
	modules := staticWorkflowModules()
	seen := map[string]bool{}
	for _, module := range modules {
		seen[module.ID] = true
	}
	for _, cmd := range commands {
		if seen[cmd.Command] {
			continue
		}
		module, err := mappedRegistryModule(cmd)
		if err != nil {
			return nil, err
		}
		modules = append(modules, module)
		seen[cmd.Command] = true
	}
	sort.Slice(modules, func(i, j int) bool { return modules[i].ID < modules[j].ID })

	var b strings.Builder
	b.WriteString("// Code generated by cobragen; DO NOT EDIT.\n\npackage commands\n\nimport (\n")
	b.WriteString("\t\"github.com/TencentCloudAgentRuntime/ags-cli/internal/command\"\n")
	for _, module := range modules {
		fmt.Fprintf(&b, "\t%s %q\n", module.Alias, module.Path)
	}
	b.WriteString(")\n\nfunc Registry() (*command.Registry, error) {\n")
	b.WriteString("\tregistry := command.NewRegistry()\n")
	b.WriteString("\tfor _, module := range []command.Module{\n")
	for _, module := range modules {
		fmt.Fprintf(&b, "\t\t%s.%s(),\n", module.Alias, module.Symbol)
	}
	b.WriteString("\t} {\n")
	b.WriteString("\t\tif err := registry.Register(module); err != nil {\n")
	b.WriteString("\t\t\treturn nil, err\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn registry, nil\n")
	b.WriteString("}\n")
	return gofmt("internal/commands/registry.generated.go", []byte(b.String()))
}

func mappedRegistryModule(cmd commandModel) (registryModule, error) {
	parts := strings.Split(cmd.Command, ".")
	dirParts := make([]string, len(parts))
	for i, p := range parts {
		dirParts[i] = strings.ReplaceAll(p, "-", "")
	}
	symbol, err := registrySymbolForCommandDir(filepath.Join("internal", "commands", filepath.Join(dirParts...)))
	if err != nil {
		return registryModule{}, err
	}
	return registryModule{
		ID:     cmd.Command,
		Alias:  registryAlias(dirParts),
		Path:   "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/" + strings.Join(dirParts, "/"),
		Symbol: symbol,
	}, nil
}

func staticWorkflowModules() []registryModule {
	ids := []string{
		"api.call",
		"instance.browser.vnc",
		"instance.code.run",
		"instance.debug",
		"instance.exec",
		"instance.file.download",
		"instance.file.upload",
		"instance.get",
		"instance.login",
		"instance.mobile.adb",
		"instance.mobile.connect",
		"instance.mobile.disconnect",
		"instance.mobile.list",
		"instance.mobile.tunnel",
		"instance.proxy",
		"tool.get",
		"tool.fork",
	}
	modules := make([]registryModule, 0, len(ids))
	for _, id := range ids {
		parts := strings.Split(id, ".")
		modules = append(modules, registryModule{
			ID:     id,
			Alias:  registryAlias(parts),
			Path:   "github.com/TencentCloudAgentRuntime/ags-cli/internal/commands/" + strings.Join(parts, "/"),
			Symbol: "Module",
		})
	}
	return modules
}

func registrySymbolForCommandDir(dir string) (string, error) {
	commandFile := filepath.Join(dir, "command.go")
	data, err := os.ReadFile(commandFile)
	if err == nil {
		if bytes.Contains(data, []byte("func Module(")) {
			return "Module", nil
		}
		return "", fmt.Errorf("%s exists but does not export Module()", commandFile)
	}
	if !os.IsNotExist(err) {
		return "", err
	}
	return "GeneratedModule", nil
}

func registryAlias(parts []string) string {
	return strings.Join(parts, "")
}

func gofmt(path string, src []byte) ([]byte, error) {
	out, err := format.Source(src)
	if err != nil {
		return src, fmt.Errorf("format %s: %w\n%s", path, err, src)
	}
	return out, nil
}
